### ISSUE TITLE
New integrations anytime soon?

### ISSUE THREAD

**Issue by DjxDeaf** [DataDog/puppet-datadog-agent#185]
Hi,

I've seen on several issues/requests that you are going to push a major release of integrations.
The problem is that at the moment there are very few supported services from those we need.

I would gladly help contribute new integrations but from what I've seen, things are delayed until the major release is out.

My question is, what is next? should I start working on integrations or do you have an ETA?

Anyway, thanks for the great job you did so far!

Eliran

**Comment by truthbk** [comment]
@DjxDeaf thank you for using our puppet module and your concern for its state :) We've been holding back adding new integrations because we have some relatively big change in the pipeline, but it has been taking a little longer than expected - that's why we've been holding back a bit. We did issue a bugfix release `1.7.1` yesteday, because there were some pressing issues that had to be addressed. We will probably hold off a few more weeks hoping the new changes will be ready, and if it's not the case, I will make sure we merge in the PRs you're referring to in `1.8.0`. 

I'd recommend you wait a bit, if you can. But if you wish to submit some PR's, when the time comes we can work together to make it fit with any changes in the module.

Thanks for the interest.

**Comment by DjxDeaf** [comment]
@truthbk Thanks for your Reply :)
We do have some massive requirements from this module, but I don't really see the point of having to develop them when they are soon to be broken (With your new integration)

In the meanwhile, we are doing the changes locally and once you do the big release, we can work together to make sure everything is defined as we think it should

Thanks!
