### ISSUE TITLE
Use full GPG key fingerprints, instead of the known-vulnerable short key ID

### ISSUE THREAD

**Issue by pid1** [DataDog/puppet-datadog-agent#330]
This is fixed for Ubuntu in https://github.com/DataDog/puppet-datadog-agent/pull/329

**Comment by truthbk** [comment]
Thanks for the PR @pid1 - we can add the full key ID.

**Comment by kosteva** [comment]
this fix, it seems to me, results in the puppet node constantly being changed, since the `unless` in `/manifests/ubuntu/install_key.pp` never gets satisfied: `apt-key` in this case is returning the older short key ids:
```pub   2048R/C7A7DA52 2011-03-16 [expires: 2018-03-04]
pub   4096R/382E94DE 2016-06-29 [expires: 2022-06-28]
```
so the grep is never satisfied (so the key is imported every puppet run), resulting in every node being marked changed every run.

i'm not sure what the right syntax to send to `apt-key` safely would be. I'm running Ubuntu 16.04 for this test.

**Comment by truthbk** [comment]
@kostas0 thank you for reporting this.... funny I didn't get this in testing. I'll explore a little further... We definitely don't want to make the manifest chatty. Thanks for bringing it up.

**Comment by bitfield** [comment]
`unless  => "/usr/bin/apt-key export ${name} | grep 'BEGIN PGP PUBLIC KEY BLOCK'",` does the trick for me.

**Comment by diranged** [comment]
We just ran into this issue when we updated the module on our end -- we got repeated puppet runs that always changed the resource. This should be reverted until a fix is merged IMO.

Is there a reason that this module doesn't use the github.com/puppetlabs/puppetlabs-apt module for managing the repositories and GPG keys? We'd be happy to submit a PR if there is no objection.

(CC: @nehalrp)

**Comment by truthbk** [comment]
Issues regarding the key fingerprints, chatty behavior, etc should've been addressed with `>=2.0` (and perhaps some of the latter `1.x` releases). We've since moved to using the `apt` module @diranged was talking about. Didn't experience any related issues during testing, so I'm going to close this. Thank you all @bitfield @kosteva
