### ISSUE TITLE
apt-get update does not get called on agent version updates

### ISSUE THREAD

**Issue by stlava** [DataDog/puppet-datadog-agent#383]
Going between minor versions does not cause an apt-get update to be called. So unless the system has run it (successfully) then the install will fail.

**Comment by truthbk** [comment]
Note taken. That said, it's really not the duty of puppet manifests to compulsively call `apt-get update` due to the system/network overhead it introduces. 

We could maybe address this somehow when the `apt` puppetlabs module is introduced in the next release as it has options to call `apt-get update` with some periodicity. I'll keep the issue open while we decide how to tackle this.

**Comment by truthbk** [comment]
@stlava I'm going to close this for now. As I mentioned earlier, `apt-get update` is a costly operation both in time and network resources and should not be called in every run. We could _maybe_ add a parameter to enable this behavior, but this would not typically be expected (and there might be other ways for you to achieve this if you wish: http://timjrobinson.com/puppet-how-to-force-apt-get-update/ 
 https://stackoverflow.com/questions/10845864/run-apt-get-update-before-installing-other-packages-with-puppet) so I'm going to close this.
