### ISSUE TITLE
Proxy settings are ignored for agent v6

### ISSUE THREAD

**Issue by atayts** [DataDog/puppet-datadog-agent#441]
Proxy settings are completely ignored for the new, v6, agent. They are missing in [$_agent_config](https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/init.pp#L547). Also beware that in the new agent HTTP and HTTPS proxies are independent values, while in the datadog_agent class they are still represented as one.

**Comment by ipleten** [comment]
collect_ec2_tags is missed too.

**Comment by truthbk** [comment]
Hi guys, 

Please note that you can pass any additional options needed in your `datadog.yaml` via the `agent6_extra_options` hash parameter. It was meant to be flexible enough to accomodate for any currently unsupported agent6 options. Because the puppet module is meant to be backward compatible it wasn't straight forward providing a consistent interface for both agents without making breaking changes, hence the presence of parameters that only apply directly to agent5. 

We can probably fix `collect_ec2_tags`, but for proxy I just recommend you pass:
```
$agent6_extra_options = {
    'collect_ec2_tags' => true,
    'proxy' => {
          'http'    => 'http(s)://user:password@foo:3128',
          'https'  => 'http(s)://user:password@bar:3128',
     }
``` 
That should then be enforced.

**Comment by truthbk** [comment]
Adding some deprecation notices here: https://github.com/DataDog/puppet-datadog-agent/pull/446
