### ISSUE TITLE
the additional_checksd parameter does not make it into the agent 6 config

### ISSUE THREAD

**Issue by gotyaoi** [DataDog/puppet-datadog-agent#510]
Adding the additional_checksd parameter to our config silently does nothing for agent 6. This seems to be because it's not included in the $_agent_config hash at https://github.com/DataDog/puppet-datadog-agent/blob/master/manifests/init.pp#L665.

**Comment by gotyaoi** [comment]
Confirmed, the following change brings additional_checksd into the config as expected:

```
diff --git a/modules/datadog_agent/manifests/init.pp b/modules/datadog_agent/manifests/init.pp
index 9359ed2..ed3bde9 100644
--- a/modules/datadog_agent/manifests/init.pp
+++ b/modules/datadog_agent/manifests/init.pp
@@ -678,6 +678,7 @@ class datadog_agent(
       'log_file' => $agent6_log_file,
       'log_level' => $log_level,
       'tags' => unique(flatten(union($_local_tags, $_facts_tags))),
+      'additional_checksd' => $additional_checksd,
     }

     $agent_config = deep_merge($_agent_config, $extra_config)```

**Comment by truthbk** [comment]
Thank you @gotyaoi, sorry about this! We appreciate the investigation and proposed fix. If you have the time to open a PR it would be awesome, I would love you to get the credit for fixing this in the git history. Otherwise we'll fix it for the next minor or bugfix release (whatever happens first).

🙇
