### ISSUE TITLE
Unable to manage datadog service when dd-trace-dotnet APM is installed

### ISSUE THREAD

**Issue by alexberry** [DataDog/puppet-datadog-agent#609]
We use https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.11.0 and, given there is no module to support it, have written one that manages package installation and ensures the service is started.

Unfortunately, the dd-trace-dotnet agent sets up a dependency on the datadog service, such that when puppet runs the datadog agent module crashes out as it is no longer able to manage the service state on windows:

```powershell
Error: /Stage[main]/Datadog_agent::Windows/Service[datadogagent]: Failed to call refresh: Failed to transition the datadogagent service to the SERVICE_STOPPED state. Detail: Failed to send the SERVICE_CONTROL_STOP signal to the service.
Its current state is SERVICE_RUNNING. Failed with:  A stop control has been sent to a service that other running services are dependent on.
Error: /Stage[main]/Datadog_agent::Windows/Service[datadogagent]: Failed to transition the datadogagent service to the SERVICE_STOPPED state. Detail: Failed to send the SERVICE_CONTROL_STOP signal to the service. Its current state is SER
VICE_RUNNING. Failed with:  A stop control has been sent to a service that other running services are dependent on.
```

This appears to be because the service resource in puppet doesn't manage dependant services, and so just gets returned a state it can't deal with.

As it stands, without forking and managing the module myself, I can't see how best to resolve this. There are no built in params to avoid the module managing the agent's service state (so that I could manage it externally with a script).

Has this use case been covered before and I'm missing something?

**Comment by albertvaka** [comment]
Hi @alexberry,

Thanks for reporting this! I agree this is a reasonable use case we should support. I'm not sure how to fix the problem you are facing, though...

My first thought was to do something like this: https://github.com/DataDog/puppet-datadog-agent/commit/390faf045e9a24732f312d9713e028c64f90a2b5 which removes the `ensure => running` on the service, but that's probably not enough since your problem seems to come from the `notify => Service[...]` events. We could also remove those but that seems a bit more convoluted code-wise.  What do you think?

An alternative would be to add support for installing and running `dd-trace-dotnet` from this module. If you are willing to share the package you wrote, maybe we can add it to this module which should make it easier to solve the dependency problems.

**Comment by ernstae** [comment]
With Datadog version 6 and above on Windows, there are two dependent services for DatadogAgent, and when a change to the configuration file is made, Puppet attempts to restart the DatadogAgent.  However, that generates an error related to the dependencies.

Example:
```
Error: /Stage[main]/Datadog_agent/Service[datadog-agent]: Failed to call refresh: Failed to transition the DatadogAgent service to the SERVICE_STOPPED state. Detail: Failed to send the SERVICE_CONTROL_STOP signal to the service. Its current state is SERVICE_RUNNING. Reason for failure::  A stop control has been sent to a service that other running services are dependent on.
Error: /Stage[main]/Datadog_agent/Service[datadog-agent]: Failed to transition the DatadogAgent service to the SERVICE_STOPPED state. Detail: Failed to send the SERVICE_CONTROL_STOP signal to the service. Its current state is SERVICE_RUNNING. Reason for failure::  A stop control has been sent to a service that other running services are dependent on.

```

With regards to restarting the service, it can be done in Powershell with a `Restart-Service -Force DatadogAgent` but not sure there is a puppet provider setting for that to rely on.

**Comment by albertvaka** [comment]
I wrote a fix for the failing service restart due to dependent services running:

https://github.com/DataDog/puppet-datadog-agent/pull/681
