### ISSUE TITLE
http_check doesn't support multiple instances

### ISSUE THREAD

**Issue by ordenull** [DataDog/puppet-datadog-agent#65]
The HTTP check here is declared as a class, this means that only one can be declared on a host. Could you please convert this to a define as I have in my fork (which you cherry-picked):

https://github.com/ordenull/puppet-datadog-agent/blob/master/manifests/defines/http_check.pp
https://github.com/ordenull/puppet-datadog-agent/blob/master/templates/http_check.yaml.erb

The pattern to declare resources as defines is much more puppet friendly and really should apply to all other checks as well. There is also another pattern in use by the process check. It does allow multiple process checks to be defined, however because it wraps them all in the same class it prevents the use of if statements in node definitions such as follows:

if ( defined( Class['Apache'] ) ) {
  datadog::process { 'apache2':
    name => 'apache2',
    search_string => 'apache2',
}

if ( defined( Class['Varnish'] ) ) {
  datadog::process { 'varnish':
    name => 'varnish',
    search_string => 'varnish',
}

**Comment by LeoCavaille** [comment]
Hi @ordenull thanks a lot for filing this and offering a solution.
It looks like a good solution, probably better than #40 and also better if we see https://docs.puppetlabs.com/guides/best_practices.html#classes-vs-defined-types.
This would require a major version release because it would break the existing manifests.
I'll discuss with my colleagues about this one, but it looks like it's worth it. Thanks!

**Comment by truthbk** [comment]
@ordenull we addressed this in #176 and you should be good to go with version `1.7.0` of the module. It's not exactly the approach you proposed, but it addressed the issue without introducing backward incompatibilities.
