### ISSUE TITLE
Every second execution of puppet fails

### ISSUE THREAD

**Issue by ipolishchuk** [DataDog/puppet-datadog-agent#80]
Every second execution of puppet removed datadog_agent package, and fails. 
We use commit 3cffbcfc6102c8cd982b9004e46fda57c19f4cf4 plus https://github.com/DataDog/puppet-datadog-agent/pull/78 on top of it, but this pull request change does not touch the affected area.
So, for the half of the time, we don't even have the  datadog_agent package installed. 
This part in the redhat.pp causes every second execution of puppet to fail:

    package { 'datadog-agent-base':
      ensure => absent,
      before => Package['datadog-agent'],
    }

We don't have datadog-agent-base, but this code by some reason deletes datadog-agent package, including dd_user. Here is the relevant portion of the puppet log:

Info: Applying configuration version '1427837407'
Debug: Prefetching yum resources for package
Debug: Executing '/bin/rpm --version'
Debug: Executing '/bin/rpm -qa --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Executing '/bin/rpm -q datadog-agent-base --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n'
Debug: Executing '/bin/rpm -q datadog-agent-base --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n --whatprovides'
Debug: Executing '/bin/rpm -e datadog-agent-5.2.2-1.x86_64'
Notice: /Stage[main]/Datadog_agent::Redhat/Package[datadog-agent-base]/ensure: removed
Debug: /Stage[main]/Datadog_agent::Redhat/Package[datadog-agent-base]: The container Class[Datadog_agent::Redhat] will propagate my refresh event

After that,  puppet fails at init.pp:
Error: Could not find user dd-agent
Error: /Stage[main]/Datadog_agent/File[/etc/dd-agent/datadog.conf]/owner: change from 498 to dd-agent failed: Could not find user dd-agent 

With a next puppet execution, the datadog_agent package gets reinstalled and exection completes normally:
Debug: Prefetching inifile resources for yumrepo
Debug: Executing '/bin/rpm -q datadog-agent --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n'
Debug: Executing '/bin/rpm -q datadog-agent --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n --whatprovides'
Debug: Package[datadog-agent](provider=yum): Ensuring => latest
Debug: Executing '/usr/bin/yum -d 0 -e 0 -y install datadog-agent'
Notice: /Stage[main]/Datadog_agent::Redhat/Package[datadog-agent]/ensure: created

**Comment by morganfletcher** [comment]
This is a problem for us.

**Comment by LeoCavaille** [comment]
Hey @ipolishchuk @morganfletcher. Thanks for reporting this. I'll investigate, the `remove datadog-agent-base` package action is a compatibility action for people who used to run CentOS < 6.
What are you guys running?

**Comment by morganfletcher** [comment]
We are on AWS linux, which is similar to redhat/centos.

**Comment by ipolishchuk** [comment]
I should add, Amazon linux is probably closer to RH 7 than <6. 
We also running Redhat 6.

**Comment by ipolishchuk** [comment]
@LeoCavaille, did you have a chance to look at this problem? 
We need to run puppet manually to make sure that we have an odd number of executions and datadog agent is installed back after being removed by 'datadog-agent-base' ensure => absent. That is pretty annoying, becayse we also cannot run puppet on schedule for this reason.

**Comment by LeoCavaille** [comment]
@ipolishchuk I have tried to repro but so for no luck (on CentOS 6/7)... Do you have a manifest snippet handy (with API keys and sensible info redacted of course) that triggers that? Is it a simple instantiation of the `datadog_agent` class?

**Comment by morganfletcher** [comment]
Léo, here is a snippet of code the calls the datadog_agent class:


  class { 'datadog_agent':
    api_key => '------------------------------------------',
    host    => $::ec2_instance_id
  } ->
  class { 'datadog_agent::integrations::solr':
    port => 8081,
  }

We have datadog_agent configured as a submodule. I see this SHA in a git
log of that submodule:

commit 3cffbcfc6102c8cd982b9004e46fda57c19f4cf4
Merge: 4f60315 e25a487
Author: Léo Cavaillé <leo@cavaille.net>
Date:   Tue Feb 24 14:12:37 2015 -0500

    Merge pull request #72 from DataDog/leo/12changelog

    Prepare 1.2.0 release


Here are two sequential puppet runs:

+ puppet agent --onetime --verbose --ignorecache --no-daemonize
--no-usecacheonfailure --detailed-exitcodes
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for qasolrmaster-ba81c973.qa.us-west-2.pwr
Info: Applying configuration version '1428449404'
Notice: /Stage[main]/Datadog_agent::Redhat/Package[datadog-agent]/ensure:
created
Notice: /Stage[main]/Datadog_agent/File[/etc/dd-agent]/owner: owner changed
'dd-agent' to 'root'
Notice: Finished catalog run in 51.04 seconds

+ puppet agent --onetime --verbose --ignorecache --no-daemonize
--no-usecacheonfailure --detailed-exitcodes
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for qasolrmaster-ba81c973.qa.us-west-2.pwr
Info: Applying configuration version '1428449404'
Notice:
/Stage[main]/Datadog_agent::Redhat/Package[datadog-agent-base]/ensure:
removed
Error: Could not find user dd-agent
Error: /Stage[main]/Datadog_agent/File[/etc/dd-agent/datadog.conf]/owner:
change from 498 to dd-agent failed: Could not find user dd-agent
Notice:
/Stage[main]/Datadog_agent::Integrations::Solr/File[/etc/dd-agent/conf.d/solr.yaml]:
Dependency File[/etc/dd-agent/datadog.conf] has failures: true
Warning:
/Stage[main]/Datadog_agent::Integrations::Solr/File[/etc/dd-agent/conf.d/solr.yaml]:
Skipping because of failed dependencies
Notice: /Stage[main]/Datadog_agent::Redhat/Service[datadog-agent]:
Dependency File[/etc/dd-agent/datadog.conf] has failures: true
Warning: /Stage[main]/Datadog_agent::Redhat/Service[datadog-agent]:
Skipping because of failed dependencies
Notice: Finished catalog run in 27.89 seconds


This is on AWS, puppet 3.7.1. Let me know if you want debug on the puppet
runs.

Morgan

**Comment by LeoCavaille** [comment]
@ipolishchuk @morganfletcher I might have identified the problem, it sits in the metadata of our RPM where we say `Provides: datadog-agent-base` and in some cases it looks like `yum` tries to remove `datadog-agent` when we ensure that `datadog-agent-base` is absent. I am building a new rpm with a fix which should avoid that.
On my CentOS 7 machine, this doesn't happen though (I run yum 3.4.3-125 and rpm 4.1.11-25). For posterity, I generated a relationship graph with `--graph` http://chiron.gb2n.org/datadog/puppet/expanded_relationships.png

To confirm that could you run:

```bash
# Ensure agent is latest 5.2.2
puppet resource package datadog-agent ensure=latest
puppet resource package datadog-agent
# Should output 5.2.2-1
# Ensure datadog-agent-base is absent
puppet resource package datadog-agent-base ensure=absent
# Verify what's the state of datadog-agent
puppet resource package datadog-agent
```

**Comment by ipolishchuk** [comment]
leo, sorry, I was out of office and could not answer earlier. 
Strangely, your test passes, however, when I execute the manifest, 
it keeps removing the datadog-agent package. 
We are on 
puppet --version
3.7.4

uname -a
3.10.42-52.145.amzn1.x86_64 #1 SMP Tue Jun 10 23:46:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ipolishchuk** [comment]
I think, something is still not quite right with the rpm package: 
Execute:
#puppet resource package datadog-agent ensure=latest
Response:
Notice: /Package[datadog-agent]/ensure: created
package { 'datadog-agent':
  ensure => '5.2.2-1',
}

Execute:
#/bin/rpm -q datadog-agent-base --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n' --whatprovides
Response:
datadog-agent 1 5.2.2 1 x86_64


So, according to rpm, the datadog-agent  package provides  datadog-agent-base, at least on our version of Amazon Linux.

**Comment by truthbk** [comment]
@ipolishchuk sorry for having this thread starved in the way it has been. My apologies! Are you still experiencing the weird behavior with more recent versions of the agent and/or puppet module?

Let us know!

**Comment by ipolishchuk** [comment]
Jaime, we do not have this problem now. You can close this thread.
Thanks for checking
Igor Polishchuk

On Mon, Apr 11, 2016 at 2:37 PM, Jaime Fullaondo <notifications@github.com>
wrote:

> @ipolishchuk <https://github.com/ipolishchuk> sorry for having this
> thread starved in the way it has been. My apologies! Are you still
> experiencing the weird behavior with more recent versions of the agent
> and/or puppet module?
>
> Let us know!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DataDog/puppet-datadog-agent/issues/80#issuecomment-208573645>
>



-- 

[image: PR_Email_Logo.png]

Igor Polishchuk, Database Architect

PowerReviews <http://www.powerreviews.com/> [image: PR__Twitter_Email.png]
<https://twitter.com/PowerofReviews>
<https://www.facebook.com/PowerReviews-1514801688740277/?fref=ts> [image:
PR__LinkedIn_Email.png] <https://www.linkedin.com/company/powerreviews>

415.489.6064

**Comment by truthbk** [comment]
thanks for the feedback @ipolishchuk, closing.
